package me.andj.djsweeper.database.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.andj.djsweeper.database.bean.Recode;

import me.andj.djsweeper.database.db.RecodeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recodeDaoConfig;

    private final RecodeDao recodeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recodeDaoConfig = daoConfigMap.get(RecodeDao.class).clone();
        recodeDaoConfig.initIdentityScope(type);

        recodeDao = new RecodeDao(recodeDaoConfig, this);

        registerDao(Recode.class, recodeDao);
    }
    
    public void clear() {
        recodeDaoConfig.clearIdentityScope();
    }

    public RecodeDao getRecodeDao() {
        return recodeDao;
    }

}
